const eventData = {
    "events": [
        {
            "name": "Contrabridge",
            "city": "Cambridge",
            "country": "UK",
            "venue": "Stoneyard Centre",
            "address": "43 St Andrew's St, Cambridge CB2 3AR",
            "latitude": 52.202210,
            "longitude": 0.124630,
            "styles": ["contra"],
            "recurringEvents": [
                {
                    "date": "2024-09-28",
                    "startTime": "19:30",
                    "endTime": "23:00",
                    "bands": ["Nozzy"],
                    "callers": ["Nicola Scott"]
                },
                {
                    "date": "2024-10-26",
                    "startTime": "19:30",
                    "endTime": "23:00",
                    "bands": ["King Kontra"],
                    "callers": ["Rob Humphrey"]
                },
                {
                    "date": "2024-11-30",
                    "startTime": "19:30",
                    "endTime": "23:00",
                    "bands": ["Fiddlechicks"],
                    "callers": ["Adam Hughes"]
                }
            ],
            "links": ["https://contrabridge.org/"],
            "organisation": "Contrabridge",
            "accessibleVenue": true,
            "calling": "Gender-Free",
            "price": "£15 for supporters, £10 for standard and £7 for students or those who otherwise can't afford full price.",
            "contact": "https://contrabridge.org/contact/"
        },
        {
            "name": "Sheffield Scratch Contra",
            "city": "Sheffield",
            "country": "UK",
            "venue": "Memorial Hall",
            "address": "Forbes Rd, Hillsborough, Sheffield S6 2NW",
            "latitude": 53.401290,
            "longitude": -1.499740,
            "styles": ["contra"],
            "date": "2024-09-05",
            "startTime": "19:30",
            "endTime": "22:30",
            "links": ["https://www.facebook.com/events/1050398396434069/"]
        },
        {
            "name": "Edinburgh Contra Dance",
            "city": "Edinburgh",
            "country": "UK",
            "venue": "Columcille Centre",
            "address": "2 Newbattle Terrace, Edinburgh EH10 4RT",
            "latitude": 55.930760,
            "longitude": -3.209340,
            "styles": ["contra"],
            "date": "2024-09-07",
            "startTime": "19:45",
            "endTime": "23:00", 
            "bands": ["Sam Baxter and Heather McAslan"],
            "callers": ["Rachel Shapiro Wallace"],
            "price": "£10-£20; Under 12s go in for free!",
            "links": ["https://www.citizenticket.com/events/edinburgh-contra-dance/edinburgh-contra-dance-september-7th/"]
        },
        {
            "name": "Bristol Contra",
            "city": "Bristol",
            "country": "UK",
            "venue": "Faithspace, Redcliffe Methodist Church",
            "address": "Faithspace, Redcliffe Methodist Church, Bristol, BS1 6PB",
            "latitude": 51.448200,
            "longitude": -2.591710,
            "styles": ["contra"],
            "startTime": "19:15",
            "endTime": "23:00",
            "links": ["https://bristolcontra.wordpress.com/"],
            "details": "No upcoming dates. Please check their website for updates.",
            "organisation": "Bristol Contra",
            "price": "£6-£15"
        },
        {
            "name": "AberACED",
            "links": ["https://aberaced.wordpress.com/"],
            "date": "2024-09-07",
            "startTime": "14:30",
            "endTime": "16:30",
            "country": "UK",
            "city": "Aberystwyth",
            "venue": "Llanbadarn Fawr",
            "address": "Llanbadarn Fawr, SY23 3QX, United Kingdom",
            "latitude": 52.409776,
            "longitude": -4.062045,
            "styles": ["contra", "ecd"],
            "workshop": true,
            "social": true,
            "price": "£3",
            "organisation": "AberACED"
        },
        {
            "name": "Englefield Green contra dance",
            "links": ["https://www.ashfordfolkdancers.org.uk/contra_dances/"],
            "date": "2024-09-08",
            "startTime": "14:30",
            "endTime": "17:30",
            "country": "UK",
            "city": "Egham",
            "venue": "Jurgens Centre",
            "address": "91 Harvest Rd., Englefield Green, Egham. TW20 0QR",
            "latitude": 51.43158,
            "longitude": -0.55239,
            "styles": ["contra"],
            "workshop": false,
            "social": true,
            "bands": ["Linda Game Band"],
            "callers": ["Ivan Aitken"],
            "organisation": "Ashford Folk Dancers"
        },
        {
            "name": "Alcester Contra",
            "links": ["https://davidfolk7.wixsite.com/alcestercontras"],
            "date": "2024-09-13",
            "startTime": "19:45",
            "endTime": "22:45",
            "country": "UK",
            "city": "Alcester",
            "venue": "Greig Hall",
            "address": "Kinwarton Road, Alcester, Warwickshire, B49 6AD",
            "latitude": 52.218171,
            "longitude": -1.867962,
            "styles": ["contra"],
            "workshop": false,
            "social": true,
            "bands": ["Bearded Dragons"],
            "callers": ["Louise Siddons"],
            "price": "£4-£10",
            "organisation": "Alcester Contra"
        },
        {
            "name": "Solent Contra Dance",
            "date": "2024-09-11",
            "startTime": "20:00",
            "endTime": "22:30",
            "country": "UK",
            "city": "Shawford",
            "venue": "Parish hall",
            "address": "Pearson Lane, Shawford. SO21 2AA",
            "latitude": 51.023965,
            "longitude": -1.329002,
            "styles": ["contra"],
            "workshop": false,
            "social": true,
            "price": "£5",
            "organisation": "Solent Contra Dances",
            "links": ["https://www.facebook.com/solentcontradances/"]
        },
        {
            "name": "Harrogate Contra",
            "links": ["http://harrogatecontra.org.uk/events.html", "https://www.facebook.com/events/1435301960414231/"],
            "date": "2024-09-14",
            "startTime": "19:30",
            "endTime": "22:30",
            "country": "UK",
            "city": "Harrogate",
            "venue": "St Aelred's Church Hall",
            "address": "Woodlands Drive, Harrogate, HG2 7BE",
            "latitude": 53.992251,
            "longitude": -1.502634,
            "styles": ["contra"],
            "workshop": false,
            "social": true,
            "bands": ["Philip & Benjamin"],
            "callers": ["Charlie Turner"],
            "price": "£6-£10",
            "organisation": "Harrogate Contra"
        },
        {
            "name": "London Barndance",
            "city": "London",
            "country": "UK",
            "venue": "Cecil Sharp House",
            "address": "Cecil Sharp House, London, NW1 7AY",
            "latitude": 51.5381,
            "longitude": -0.149363,
            "styles": ["contra"],
            "price": "£15 (£13 for LBC members and concessions, £5 for under-18s)",
            "recurringEvents": [
                {
                    "date": "2024-09-14",
                    "startTime": "20:00",
                    "endTime": "23:00",
                    "bands": ["Linda Game Band"],
                    "callers": ["Adam Hughes"]
                },
                {
                    "date": "2024-10-12",
                    "startTime": "20:00",
                    "endTime": "23:00",
                    "bands": ["Old Time Contra Band"],
                    "callers": ["Diane Silver"]
                },
                {
                    "date": "2024-11-09",
                    "startTime": "20:00",
                    "endTime": "23:00",
                    "bands": ["Contrasaurus"],
                    "callers": ["Mark Elvins"]
                },
                {
                    "date": "2024-12-14",
                    "startTime": "20:00",
                    "endTime": "23:00",
                    "bands": ["King Contra String Band"],
                    "callers": ["Lynne Render"]
                }
            ],
            "links": ["https://www.barndance.org/programme.html"],
            "organisation": "London Barndance Company"
        },
        {
            "name": "Nottingham Contra Dance",
            "links": ["https://www.nfdg.org.uk/club_dances.php"],
            "date": "2024-10-05",
            "startTime": "19:30",
            "endTime": "23:00",
            "country": "UK",
            "city": "Nottingham",
            "venue": "Woodborough Village Hall",
            "address": "Lingwood Lane, Woodborough, Nottingham, NG14 6DX",
            "latitude": 53.021465,
            "longitude": -1.060963,
            "styles": ["contra"],
            "workshop": false,
            "social": true,
            "bands": ["The Old Time Contra Band"],
            "callers": ["Diane Silver"],
            "price": "£10",
            "organisation": "Nottingham Folk Dance Group"
        },
        {
            "name": "Leeds Contra",
            "city": "Leeds",
            "country": "UK",
            "venue": "St Chads Hall",
            "address": "St Chads Hall, Otley Road, Leeds LS16 5JT",
            "latitude": 53.82861,
            "longitude": -1.584928,
            "styles": ["contra"],
            "date": "2024-09-28",
            "startTime": "19:30",
            "endTime": "23:00",
            "bands": ["Joshua and Philip Rowe"],
            "callers": ["Diane Silver (USA)"],
            "price": "£10",
            "organisation": "Leeds Contra",
            "links": ["http://www.leedscontra.freeuk.com/specialevents.html"]
        },
        {
            "name": "Lancaster Contra",
            "details": "Musicians: Heather McAslan and Edward Wallace",
            "links": ["http://lancastercontra.org.uk/events/", "https://www.facebook.com/events/710205900947385/"],
            "date": "2024-11-16",
            "startTime": "13:30",
            "endTime": "16:45",
            "country": "UK",
            "city": "Lancaster",
            "venue": "St.Paul's Parish Hall, Scotforth Rd",
            "latitude": 54.034323,
            "longitude": -2.79528,
            "styles": ["contra"],
            "workshop": false,
            "social": true,
            "bands": ["Edward Wallace & Heather McAslan"],
            "callers": ["Lisa Heywood"],
            "price": "£10-£15",
            "organisation": "Lancaster Contra"
        },
        {
            "name": "Exeter Contra",
            "city": "Exeter",
            "country": "UK",
            "venue": "Venue TBA",
            "address": "Exeter, UK",
            "latitude": 50.668809,
            "longitude": -3.537793,
            "styles": ["contra"],
            "date": "2024-10-19",
            "startTime": "19:30",
            "endTime": "23:00",
            "details": "Details TBD",
            "links": ["https://barndancecaller.net/exetercontra.html"]
        }
    ]
};
